// Generated by Xata Codegen 0.29.4. Please do not edit.
import { buildClient } from '@xata.io/client';
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from '@xata.io/client';
import dotenv from 'dotenv';
dotenv.config();

const tables = [
  {
    name: 'sets',
    columns: [
      { name: 'title', type: 'string' },
      { name: 'description', type: 'text' },
      { name: 'private', type: 'bool' },
      { name: 'image', type: 'file', file: { defaultPublicAccess: true } },
      { name: 'creator', type: 'string' },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Sets = InferredTypes['sets'];
export type SetsRecord = Sets & XataRecord;

export type DatabaseSchema = {
  sets: SetsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: process.env.databaseURL,
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
